### ISSUE TITLE
Exit cypress when there is a failure

### ISSUE THREAD

**Issue by alexandrzavalii** [javierbrea/cypress-fail-fast#25] opened 2020-12-16 11:40 UTC
**Is your feature request related to a problem? Please describe.**
I would like to abort all tests suits, and exit from cypress task as soon as there is one failure.

Currently, cypress-fail-fast will only abort all the tests in one file, but it will continue with other test files

**Comment by javierbrea** [comment] 2020-12-16 15:35
Hi @alexandrzavalii,

That is not the expected behavior. It should continue executing the rest of spec files, but skipping all tests too.

Here is a screenshot from the [last E2E tests execution in the package build pipeline](https://github.com/javierbrea/cypress-fail-fast/runs/1532785090?check_suite_focus=true), in which you can notice how tests in the second file were skipped too:

![image](https://user-images.githubusercontent.com/983381/102368863-a2575a00-3fbb-11eb-92a1-819512fce44e.png)

Tests are being executed successfully with Cypress versions 5.6.0 and 6.1.0, both of them tested also with Node.js versions 12.19.0, 14.15.0 and 15.2.0.

Could you please provide more details about how are you loading the plugin, and your current Node.js and Cypress versions in order to try to reproduce the issue?

**Comment by tobloef** [comment] 2021-01-14 14:16
I have the same issue, but it only when I use `cypress run` and not `cypress open`. With `cypress open`, it will step all specs from being tested when a test fails, but with `cypress run` it only stops the sec with the failed test.

If this is a bug, what kind of info would you like in order to solve the issue?

**Comment by AdrianoFerrari** [comment] 2021-02-09 01:45
I think what the OP means, is that I'd hope/expect for Cypress to simply exit right away on first failure. Even though the remaining tests *are* skipped, there's still a setup/teardown for each one (maybe in the before blocks?), that takes time.

In other words, cypress-fail-fast is useful, and I think it would be even more useful if it failed faster (immediate abort/exit on failure).

**Comment by javierbrea** [comment] 2021-02-09 06:17
Hi @AdrianoFerrari,

Yes, it would be better to exit faster, but for the moment this is the only approach I found that works, because it is not possible to stop the whole process from Cypress. Anyway, aborting immediately wouldn't be a good solution in my opinion, as it would be desirable to continue executing `after` hooks, for example (as it is described in #61).

About the `before` hooks, there is another issue opened that I'll try to fix as soon as possible (#52).

Anyway, I'll continue investigating to find a better solution. Thanks for your feedback!

**Comment by javierbrea** [comment] 2021-02-21 21:32
@AdrianoFerrari @alexandrzavalii Before hooks in the rest of files are also skipped from [release v2.2.0](https://github.com/javierbrea/cypress-fail-fast/releases/tag/v2.2.0).

**Comment by javierbrea** [comment] 2021-04-07 06:59
Hi @AdrianoFerrari and @alexandrzavalii , I am going to close this issue because the `before` hooks are also skipped now, and stopping the Cypress process would prevent executing the `after` hooks, which might be a problem.
Thanks for your feedback! 🙂

**Closed by javierbrea** 2021-04-07 06:59 UTC
Labels: stage: awaiting response

**Comment by alexandrzavalii** [comment] 2021-05-14 14:05
am I right in saying that its not really aborting the tests but rather skipping them?

**Comment by javierbrea** [comment] 2021-05-18 05:36
Yes @alexandrzavalii , you're right. From the description of the plugin: _"Enables fail fast in Cypress, skipping the rest of tests on first failure."_

For the moment, Cypress does not provide a way to abort the execution, and, anyway, it might not be desirable in many scenarios, as mentioned above.
