### ISSUE TITLE
Tests are failed if before hook is failed

### ISSUE THREAD

**Issue by VadimCWebLabs** [javierbrea/cypress-fail-fast#296] opened 2024-07-08 10:12 UTC
**Describe the bug**
If before hook is failed, then all the tests in spec will fail

**To Reproduce**
1) create spec
2) create beforEach hook
3) fail beforEach Hook
4) see all the tests in spec will fail in statistics

**Expected behavior**
If before hook is failed all tests in spec should be skipped

**Comment by javierbrea** [comment] 2024-08-05 04:49
Hi @VadimCWebLabs ,
When a before hook fails, the plugin force the next test to fail in order to be able to store the "skip" flag properly, so other spec files can be also skipped. This was not working properly in Cypress 13, and the rest of tests were being executed normally. Maybe in your case were all failing because of the failure in the your "before" hook? Anyway, I have fixed this problem in the [release v7.1.1](https://github.com/javierbrea/cypress-fail-fast/releases/tag/v7.1.1). So, I will close this issue. If this is not related to the problem fixed there and you continue experiencing problems, please open another issue providing all details about your Cypress version, logs, etc, and, ideally, a reproducible example in a repository.

**Closed by javierbrea** 2024-08-05 04:49 UTC
