### ISSUE TITLE
Avoid clashing global types between Cypress and Jest

### ISSUE THREAD

**Issue by aleksey-ilin** [javierbrea/cypress-fail-fast#235] opened 2022-08-11 14:28 UTC
Hello. Thank you for this library.
**Describe the bug**
I use cypress-fail-fast in a project with common cypress config for other projects. It has jest test for custom cypress commands. After install cypress-fail-fast I have typescript error
"Property 'toEqual' does not exist on type 'Assertion'. Did you mean 'equal'? ts(2551)
index. d. ts (206, 9): 'equal' is declared here."
If delete `/// <reference types="cypress" />` in the plugin. d. ts and index. d. ts errors disappears. So I suggest delete these two lines from cypress-fail-fast. I tried it and it is ok.

**Comment by javierbrea** [comment] 2022-08-11 15:55
Hi @aleksey-ilin , could you please provide more details about your specific Cypress version and/or TypeScript configuration in order to be able to reproduce the issue?

The package includes TypeScript compilation as a part of the E2E tests and this error is not happening in the tests. So, I need to reproduce the issue before trying to fix it.

About your proposed solution, I'm not an expert in TypeScript, could you please explain deeper why would this fix the issue? Would types of the plugin continue working when the reference is removed? Following the Cypress guidelines for adding types for custom commands (which is not exactly the case, but may be very similar to extending other Cypress type declarations), [they include the reference in their examples](https://docs.cypress.io/guides/tooling/typescript-support#Adding-child-or-dual-commands).

Thanks in advance! 😃

**Comment by aleksey-ilin** [comment] 2022-08-12 09:42
I reproduced this error.
https://playcode.io/940385

I read about Triple-Slash Directives in typescript documentation and did not find how it affects on types of projects. I suggest than Triple-Slash Directives work another way that types in tsconfig, but how I do not say right now. I tried delete /// <reference types="cypress" /> in cypress-fail-fast, no errors appeared, but errors disappeared in my project.

**Comment by javierbrea** [comment] 2022-08-12 10:59
Thanks for reproducing it @aleksey-ilin

Errors disappearing on your Jest files can mean a lot of things. One of them could be that the types of this package are not working any more, so they don't produce a conflict with Jest types. I have noticed that you haven't included this package types in your Cypress TypeScript config. But this package needs its types to work properly, because it extends some Cypress types that may be required to use some plugin features.

For example, now that you have removed the slashes, could you try to use the spec configuration of this plugin in a Cypress test? If plugin types are not loaded properly, it would produce an error. For example:

```js
describe('My First Cypress Test', () => {
  it('Does not do much!',{failFast: {enabled: true}}, () => {
    expect(true).to.equal(true)
  })
})
```

So, before making any modification it is required to test all possible scenarios.

After some fast researching, I've found similar issues affecting to other Cypress users, that are not related to this plugin: https://github.com/cypress-io/cypress/issues/22059. Some answers in that issue suggest to use the `exclude` TypeScript option to avoid loading Cypress types in your Jest files, for example:

```json
{ "exclude": ["node_modules", "cypress", "cypress-fail-fast"] }
```

Anyway, I will investigate further, thanks for the example, because I didn't understand well that the issue was related to Cypress types being in conflict with separated Jest TypeScript tests.

**Comment by javierbrea** [comment] 2022-08-16 07:13
I have created a branch for testing this based on the @aleksey-ilin example: https://github.com/javierbrea/cypress-fail-fast/tree/test-235-ts-types-cypress-10

I have added Cypress and Jest tests using next libraries versions:
- Cypress: 10.5.0
- Jest: 28.1.3
- ts-jest: 28.0.8
- typescript: 4.7.2
- @types/jest: 28.1.7

I also have created a Github workflow that executes Cypress tests, unit tests and the `tsc` command on Ubuntu-latest using Node.js 16.14.0: https://github.com/javierbrea/cypress-fail-fast/actions/runs/2865891853.

Everything seems to be working properly, and there are no type errors in the Jest files. As it can be seen in the branch, I didn't even have to configure the TypeScript `exclude` property.

**Comment by aleksey-ilin** [comment] 2022-08-16 13:52
I decided this problem. I create another tsconfig for jest tests. But I did not understand why and how did it help. So I will create fully executable examples on this week. I want to learn this problem deeper.

**Comment by aleksey-ilin** [comment] 2022-08-18 10:11
I created a fully executable example. This is a library with common settings for cypress. It includes several cypress plugin and typescript error on jest test. If delete cypress-fail-fast or delete `/// <reference types="cypress" />` in cypress-fail-fast, so error disappear.
https://github.com/aleksey-ilin/cypress-fail-fast-clashing-global-types

**Comment by javierbrea** [comment] 2022-08-18 12:57
Hi again @aleksey-ilin ,

First of all, you have a problem in the dependencies. The `ts-jest` version that you are using has not been tested with the `jest` version in your dependencies:

<img width="1087" alt="Captura de pantalla 2022-08-18 a las 13 16 52" src="https://user-images.githubusercontent.com/983381/185383291-42cf5c00-6b83-4d59-91cc-f04478b5e385.png">

Anyway, even when it is not recommended to open an issue when you have such warning messages, the problem seems to be related to another thing:

In the root `tsconfig.json` file you are loading both types for "jest" and "cypress" (which [may be a problem by itself, as it is described in the Cypress documentation](https://docs.cypress.io/guides/tooling/typescript-support#Clashing-types-with-Jest)). You are also including in the TypeScript config all files from the "src" and "jest" folders, and you are importing the "cypress-fail-fast" library in the `src/add-plugins.ts` file. As the `cypress-fail-fast` plugin has a dependency with "cypress" types ([which should be expressed using the triple slash directive, as it is detailed in the Cypress docs](https://docs.cypress.io/guides/tooling/typescript-support#Types-for-Custom-Commands)), then I suppose that both Cypress and Jest types are being loaded, and this produces the conflict, again, you can [checkout the Cypress documentation at this respect](https://docs.cypress.io/guides/tooling/typescript-support#Clashing-types-with-Jest).

I suppose that you are importing this plugin in your "src" folder because you're making a "plugin" being a "plugins bundle". So, taking into account that you'll very probably need to import files from the "src" folder in the "jest" folder in order to test them, creating two separated `tsconfig` files, one for the tests and another one for the src folder wouldn't solve the problem, because the conflict will arise again whenever you import the `src/add-plugins.ts` file in your Jest files (and, it would also happen if you import "cypress" in any of your test files, you can also check it).

Then, the best solution I can think of is to use explicitly the Jest `expect` and `describe` methods in your tests in order to avoid the conflict (the solution is similar to the proposed [in this post](https://glebbahmutov.com/blog/local-cypress/), but using jest locals instead of cypress locals):

```js
import { describe, expect } from '@jest/globals'

import { addPlugin } from "../src/add-plugin";

describe('addPlugin method', () => {
  it('should exist', () => {
      expect(addPlugin).toBeDefined();
  });
});
```

I have checked that this solution works without any extra modification in your repository. Anyway, I would also separate the TypeScript configurations into two separated files: one for Jest and another one for Cypress, because it is explicitly indicated in the Cypress documentation that it may produce a conflict.

About your comment _"If delete cypress-fail-fast or delete /// <reference types="cypress" /> in cypress-fail-fast, so error disappear."_, I suppose that you have not noticed that the spec files in the `cypress/integration` folder stop working when the `cypress-fail-fast` library is removed, because its types are not loaded any more.

As a summary:

* Loading both Jest and Cypress types may produce a conflict. It is a [Cypress known caveat](https://docs.cypress.io/guides/tooling/typescript-support#Clashing-types-with-Jest)
* Usually the conflict is not produced because Jest and Cypress types are not loaded together. (Jest files usually don't import the Cypress library)
* You have a conflict because you have to import the "cypress-fail-fast" library in your Jest tests, which has a dependency with "cypress", so, you can't solve the problem using separated "tsconfig" files.
* You can solve the problem by using Jest methods instead of global ones.
* This plugin has a dependency with Cypress types. The way of expressing the dependency is using triple slashes. The dependency shouldn't be removed, as far as I know. Apart from the fact that the dependency does really exist, examples in the Cypress docs about defining custom commands include it. Given the amount of users of this plugin, that I'm not a TypeScript expert, and that your specific use case is not a common one, the risk of removing it without a deeper knowledge is high.

PD: I have tested and committed all of the proposed changes to a [fork of your repository](https://github.com/javierbrea/cypress-fail-fast-clashing-global-types).

**Comment by aleksey-ilin** [comment] 2022-08-21 09:57
Hi, @javierbrea!
Thank you for detail explanation. Your suggestion about purpose of my repository exactly right. Created tsconfig for jest tests helped me, but if you will have more information about this issue, for example, why another plugin did not this typescript error, write in this issue.

**Comment by javierbrea** [comment] 2022-08-21 10:58
> Hi, @javierbrea! Thank you for detail explanation. Your suggestion about purpose of my repository exactly right. Created tsconfig for jest tests helped me, but if you will have more information about this issue, for example, why another plugin did not this typescript error, write in this issue.

You're welcome @aleksey-ilin 😃 

Well, other plugins may not produce this conflict due to multiple reasons:

* Other plugins may don't have dependency with Cypress types. This one does because it is extending Cypress' `TestConfigOverrides` interface in order to provide custom options to specs, and in the Node.js side it needs to extend Cypress plugin options.
* Other plugins may don't even have TypeScript types. For example, the other plugin you are using: `cypress-image-snapshot`
* You may be using other plugins, but you don't import them from your Jest tests. This one neither produces a conflict if you don't import it in your Jest tests, and you have TypeScript configured properly.

And, finally, I don't know if other plugins define the dependency with Cypress, which produces the conflict. But, as mentioned in my previous comment, it is a real dependency, so, I think that it shouldn't be removed to "fix" a conflict between Jest and Cypress. That conflict is not a problem of this plugin, and removing the dependency here would be only a workaround.

**Closed by javierbrea** 2022-08-21 10:58 UTC
Labels: dependencies
